# Lazy Game Servers nginx config file

server {
    listen ${EXTERNAL_PORT};
    
    location /api {
        proxy_pass http://localhost:${INTERNAL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        root ${FRONTEND_ASSETS_PATH};
        try_files $$uri /index.html;
    }
}
