; Lazy Game Servers supervisor config file

[program:lazy_game_servers]
command=${CWD}/venv/bin/python3 -OO main.py --port ${INTERNAL_PORT} --directory ${CONF_DIR}
directory=${CWD}
autostart=true
autorestart=true
stopsignal=INT
